adminlte/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace adminlte.Controllers
{
    public class LayoutController : Controller
    {
        // GET: Layout
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Boxed()
        {
            return View();
        }

        public ActionResult CollapsedSidebar()
        {
            return View();
        }

        public ActionResult Fixed()
        {
            return View();
        }

        public ActionResult TopNav()
        {
            return View();
        }
    }
}

adminlte/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using adminlte.Models;
using adminlte.DAL;

namespace adminlte.Controllers
{
    public class PagesController : Controller
    {
        public ActionResult Cadastro()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Cadastro(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                using (DirecionaCursos db = new DirecionaCursos())
                {
                    ViewBag.Escolaridade = new SelectList(db.Escolaridades, "ID", "Descricao");

                    db.Alunos.Add(aluno);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = aluno.Nome + " cadastrado com sucesso.";

            }
            return View();
        }


        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Aluno aluno)
        {
            using (DirecionaCursos db = new DirecionaCursos())
            {
                var alu = db.Alunos.Single(a => a.Email == aluno.Email && a.Senha == aluno.Senha);
                if (alu != null)
                {
                    Session["ID"] = alu.ID.ToString();
                    Session["Nome"] = alu.Nome.ToString();
                    return RedirectToAction("Logado");
                }
                else
                {
                    ModelState.AddModelError("", "Email ou senha estão incorretos!");
                }
            }
            return View();
        }

        public ActionResult Logado()
        {
            if (Session["ID"] != null)
                return View();
            else
                return RedirectToAction("Login");
        }

        // GET: Page
        public ActionResult Inicio()
        {
            return View();
        }

        public ActionResult Certificados()
        {
            return View(GoogleDriveFilesRepository.GetDriveFiles());
        }
        [HttpGet]
        public ActionResult GetGoogleDriveFiles()
        {
            return View(GoogleDriveFilesRepository.GetDriveFiles());
        }

        [HttpGet]
        public ActionResult GetGoogleDriveFiles1()
        {
            return View(GoogleDriveFilesRepository.GetDriveFiles());
        }


        [HttpGet]
        public ActionResult GetGoogleDriveFiles2()
        {
            return View(GoogleDriveFilesRepository.GetDriveFiles());
        }

        [HttpPost]
        public ActionResult DeleteFile(GoogleDriveFile file)
        {
            GoogleDriveFilesRepository.DeleteFile(file);
            return RedirectToAction("Certificados");
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            GoogleDriveFilesRepository.FileUpload(file);
            return RedirectToAction("Certificados");
        }

        public void DownloadFile(string id)
        {
            string FilePath = GoogleDriveFilesRepository.DownloadGoogleFile(id);

            Response.ContentType = "application/zip";
            Response.AddHeader("Content-Disposition", "attachment; filename=" + Path.GetFileName(FilePath));
            Response.WriteFile(System.Web.HttpContext.Current.Server.MapPath("~/GoogleDriveFiles/" + Path.GetFileName(FilePath)));
            Response.End();
            Response.Flush();
        }


        [HttpGet]
        public ActionResult GetContainsInFolder(string folderId)
        {
            return View(GoogleDriveFilesRepository.GetContainsInFolder(folderId));
        }

        [HttpPost]
        public ActionResult CreateFolder(String FolderName)
        {
            GoogleDriveFilesRepository.CreateFolder(FolderName);
            return RedirectToAction("GetGoogleDriveFiles1");
        }


        [HttpPost]
        public ActionResult FileUploadInFolder(GoogleDriveFile FolderId, HttpPostedFileBase file)
        {
            GoogleDriveFilesRepository.FileUploadInFolder(FolderId.Id, file);
            return RedirectToAction("GetGoogleDriveFiles1");
        }


        [HttpGet]
        public JsonResult FolderLists()
        {
            List<GoogleDriveFile> AllFolders = GoogleDriveFilesRepository.GetDriveFolders();
            List<DDLOptions> obj = new List<DDLOptions>();

            foreach (GoogleDriveFile EachFolder in AllFolders)
            {
                obj.Add(new DDLOptions { Id = EachFolder.Id, Name = EachFolder.Name });
            }
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        public string MoveFiles(String fileId, String folderId)
        {
            string Result = GoogleDriveFilesRepository.MoveFiles(fileId, folderId);
            return Result;
        }

        public string CopyFiles(String fileId, String folderId)
        {
            string Result = GoogleDriveFilesRepository.CopyFiles(fileId, folderId);
            return Result;
        }

        public JsonResult Render_GetGoogleDriveFilesView()
        {
            Dictionary<string, object> jsonResult = new Dictionary<string, object>();
            var result = GoogleDriveFilesRepository.GetDriveFiles();
            jsonResult.Add("Html", RenderRazorViewToString("~/Views/Home/GetGoogleDriveFiles1.cshtml", result));
            return Json(jsonResult, JsonRequestBehavior.AllowGet);
        }

        public string RenderRazorViewToString(string viewName, object model)
        {
            if (model != null)
            {
                ViewData.Model = model;

            }
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

adminlte/Views/Shared/_Aside.cshtml
    <!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->
                <h3 class="control-sidebar-heading">Chat Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->

adminlte/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Copyright &copy; 2020.</strong> Todos os Direitos Reservados.
</footer>

adminlte/Views/Shared/_Header.cshtml
<header class="main-header">
    <!-- Logo -->
    <a href="@Url.Action("Dashboardv1", "Dashboard")" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>DC</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">Direciona Cursos</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    @if (Session["Aluno"] != null)
                    {
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            @*<img src="~/Content/adminlte/img/user2-160x160.jpg" class="user-image" alt="User Image">*@
                            <span class="hidden-xs">@Session["Nome"].ToString()</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="~/Content/adminlte/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                <p>
                                    @Session["Nome"].ToString()
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">Perfil</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">Sair</a>
                                </div>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <a href="@Url.Action("Login", "Pages")" class="dropdown-toggle" data-toggle="dropdown">
                            @*<img src="~/Content/adminlte/img/user2-160x160.jpg" class="user-image" alt="User Image">*@
                            <span class="hidden-xs">Logar</span>
                        </a>
                    }
                </li>
            </ul>
        </div>
    </nav>
</header>

adminlte/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title - Direciona Cursos</title>
    @Styles.Render("~/Content/css")

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
</head>
<body class="hold-transition skin-blue sidebar-mini">

    <div class="wrapper">

        @Html.Partial("_Header")

        @Html.Partial("_Sidebar")

        @RenderBody()

        @Html.Partial("_Footer")

        @Html.Partial("_Aside")
        <!-- Add the sidebar's background. This div must be placed
        immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

adminlte/Views/Shared/_Sidebar.cshtml
    <!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/Content/adminlte/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>Jhonata Tocantins</p>             
            </div>
        </div>
      
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">Navegação</li>
            <li class="@Html.IsSelected(action: "Inicio")"><a href="@Url.Action("Inicio", "Pages")"><i class="fa fa-home"></i> <span>Início</span></a></li>
            <li><a href="#"><i class="fa fa-user"></i> <span>Perfil</span></a></li>
            <li class="@Html.IsSelected(action: "Certificados")"><a href="@Url.Action("Certificados", "Pages")"><i class="fa fa-file"></i> <span>Certificados</span></a></li>
            <li class="treeview @Html.IsSelected(controller: "Tables")">
                <a href="@Url.Action("Simple", "Tables")">
                    <i class="fa fa-laptop"></i> <span>Cursos</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Html.IsSelected(action: "Acao")"><a href="@Url.Action("Acao", "Controller")"><i class="fa fa-spinner"></i> Cursando</a></li>
                    <li class="@Html.IsSelected(action: "Acao")"><a href="@Url.Action("Acao", "Controller")"><i class="fa fa-check-circle"></i> Concluídos</a></li>
                </ul>
            </li>
            <li><a href="#"><i class="fa fa-star-o"></i> <span>Favoritos</span></a></li>

            @*<li class="@Html.IsSelected(controller: "Dashboard") treeview">
                <a href="@Url.Action("Dashboardv1", "Dashboard")">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Html.IsSelected(action: "Dashboardv1")"><a href="@Url.Action("Dashboardv1", "Dashboard")"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li class="@Html.IsSelected(action: "Dashboardv2")"><a href="@Url.Action("Dashboardv2", "Dashboard")"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "Layout") treeview">
                <a href="@Url.Action("Fixed", "Layout")">
                    <i class="fa fa-home"></i>
                    <span>Início</span>
                    <span class="pull-right-container">
                        <span class="label label-primary pull-right">4</span>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Html.IsSelected(action: "TopNav")"><a href="@Url.Action("TopNav", "Layout")"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
                    <li class="@Html.IsSelected(action: "Boxed")"><a href="@Url.Action("Boxed", "Layout")"><i class="fa fa-circle-o"></i> Boxed</a></li>
                    <li class="@Html.IsSelected(action: "Fixed")"><a href="@Url.Action("Fixed", "Layout")"><i class="fa fa-circle-o"></i> Fixed</a></li>
                    <li class="@Html.IsSelected(action: "CollapsedSidebar")"><a href="@Url.Action("CollapsedSidebar", "Layout")"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "Widgets")">
                <a href="@Url.Action("Index", "Widgets")">
                    <i class="fa fa-th"></i> <span>Widgets</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-green">new</small>
                    </span>
                </a>
            </li>
            <li class="treeview @Html.IsSelected(controller: "Charts")">
                <a href="@Url.Action("Chartjs", "Charts")">
                    <i class="fa fa-pie-chart"></i>
                    <span>Charts</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Html.IsSelected(action: "Chartjs")"><a href="@Url.Action("Chartjs", "Charts")"><i class="fa fa-circle-o"></i> ChartJS</a></li>
                    <li class="@Html.IsSelected(action: "Morris")"><a href="@Url.Action("Morris", "Charts")"><i class="fa fa-circle-o"></i> Morris</a></li>
                    <li class="@Html.IsSelected(action: "Flot")"><a href="@Url.Action("Flot", "Charts")"><i class="fa fa-circle-o"></i> Flot</a></li>
                    <li class="@Html.IsSelected(action: "Inline")"><a href="@Url.Action("Inline", "Charts")"><i class="fa fa-circle-o"></i> Inline charts</a></li>
                </ul>
            </li>
            <li class="treeview @Html.IsSelected(controller: "UI")">
                <a href="@Url.Action("General", "UI")">
                    <i class="fa fa-laptop"></i>
                    <span>UI Elements</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Html.IsSelected(action: "General")"><a href="@Url.Action("General", "UI")"><i class="fa fa-circle-o"></i> General</a></li>
                    <li class="@Html.IsSelected(action: "Icons")"><a href="@Url.Action("Icons", "UI")"><i class="fa fa-circle-o"></i> Icons</a></li>
                    <li class="@Html.IsSelected(action: "Buttons")"><a href="@Url.Action("Buttons", "UI")"><i class="fa fa-circle-o"></i> Buttons</a></li>
                    <li class="@Html.IsSelected(action: "Timeline")"><a href="@Url.Action("Timeline", "UI")"><i class="fa fa-circle-o"></i> Timeline</a></li>
                    <li class="@Html.IsSelected(action: "Modals")"><a href="@Url.Action("Modals", "UI")"><i class="fa fa-circle-o"></i> Modals</a></li>
                </ul>
            </li>
            <li class="treeview @Html.IsSelected(controller: "Forms")">
                <a href="@Url.Action("General", "Forms")">
                    <i class="fa fa-edit"></i> <span>Forms</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Html.IsSelected(action: "General")"><a href="@Url.Action("General", "Forms")"><i class="fa fa-circle-o"></i> General Elements</a></li>
                    <li class="@Html.IsSelected(action: "Advanced")"><a href="@Url.Action("Advanced", "Forms")"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                    <li class="@Html.IsSelected(action: "Editors")"><a href="@Url.Action("Editors", "Forms")"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul>
            </li>
            <li class="treeview @Html.IsSelected(controller: "Tables")">
                <a href="@Url.Action("Simple", "Tables")">
                    <i class="fa fa-table"></i> <span>Tables</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Html.IsSelected(action: "Simple")"><a href="@Url.Action("Simple", "Tables")"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                    <li class="@Html.IsSelected(action: "Data")"><a href="@Url.Action("Data", "Tables")"><i class="fa fa-circle-o"></i> Data tables</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "Calendar")">
                <a href="@Url.Action("Index", "Calendar")">
                    <i class="fa fa-calendar"></i> <span>Calendar</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-red">3</small>
                        <small class="label pull-right bg-blue">17</small>
                    </span>
                </a>
            </li>
            <li class="@Html.IsSelected(controller: "Mailbox")">
                <a href="@Url.Action("Compose", "Mailbox")">
                    <i class="fa fa-envelope"></i> <span>Mailbox</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-yellow">12</small>
                        <small class="label pull-right bg-green">16</small>
                        <small class="label pull-right bg-red">5</small>
                    </span>
                </a>
            </li>
            <li class="treeview @Html.IsSelected(controller: "Examples")">
                <a href="@Url.Action("Invoice", "Examples")">
                    <i class="fa fa-folder"></i> <span>Examples</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Html.IsSelected(action: "Invoice")"><a href="@Url.Action("Invoice", "Examples")"><i class="fa fa-circle-o"></i> Invoice</a></li>
                    <li class="@Html.IsSelected(action: "PageProfile")"><a href="@Url.Action("PageProfile", "Examples")"><i class="fa fa-circle-o"></i> Profile</a></li>
                    <li><a href="@Url.Action("Login", "Examples")"><i class="fa fa-circle-o"></i> Login</a></li>
                    <li><a href="@Url.Action("Register", "Examples")"><i class="fa fa-circle-o"></i> Register</a></li>
                    <li><a href="@Url.Action("Lockscreen", "Examples")"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                    <li class="@Html.IsSelected(action: "Page404")"><a href="@Url.Action("Page404", "Examples")"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                    <li class="@Html.IsSelected(action: "Page500")"><a href="@Url.Action("Page500", "Examples")"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                    <li class="@Html.IsSelected(action: "Blank")"><a href="@Url.Action("Blank", "Examples")"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                    <li class="@Html.IsSelected(action: "Pace")"><a href="@Url.Action("Pace", "Examples")"><i class="fa fa-circle-o"></i> Pace Page</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-share"></i> <span>Multilevel</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-circle-o"></i> Level One
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-circle-o"></i> Level Two
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                </ul>
            </li>*@
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>